export type Item = {
  itemNo: string;
  description: string;
  description2?: string;
  barcode: string;
  baseUom?: string;
  stock?: number;
};

export type LedgerEntry = {
  entryNo: number;
  postingDate?: string;
  entryType?: string;
  documentType?: string;
  documentNo?: string;
  externalDocNo?: string;
  itemNo: string;
  description?: string;
  lotNo: string;
  expirationDate?: string;
  locationCode: string;
  quantity: number;
  remainingQuantity: number;
  uom?: string;
  sourceTransferId?: string; // set when this entry was generated by closing a Transfer in this app
};

export type TransferLine = {
  itemNo: string;
  description?: string;
  quantity: number;
  lotNo: string;
  expirationDate?: string;
  uom?: string;
  alreadyExp: boolean; // true if this lot is already at 60008-EXP
};

export type Transfer = {
  id: string;
  externalDocNo?: string;
  storeFrom: string;
  locationFrom: string;
  storeTo: string;
  locationTo: string;
  createdAt: string;
  closedAt?: string;
  closed: boolean;
  // applied = D365 processed this transfer (the new Ledger upload contains
  // entries tagged with this externalDocNo). Applied transfers no longer
  // reserve stock — the Ledger now reflects the move.
  applied?: boolean;
  appliedAt?: string;
  cartonNo?: string;
  note?: string;
  lines: TransferLine[];
};

export type ItemJournalEntry = {
  id: string;
  documentNo: string;            // LOT60008-YYMM### (auto-assigned, editable)
  itemNo: string;
  description?: string;
  locationCode: string;          // 60008-EXP
  quantity: number;
  uom?: string;
  // Negative Adjmt. side — the lot to undo
  oldLotNo: string;
  oldExpirationDate?: string;    // ISO YYYY-MM-DD
  // Positive Adjmt. side — the corrected lot
  newLotNo: string;
  newExpirationDate?: string;    // ISO YYYY-MM-DD
  postingDate?: string;          // set at export time, ISO YYYY-MM-DD
  createdAt: string;
  exported: boolean;
  exportedAt?: string;
  applied?: boolean;             // detected when documentNo appears in Ledger
  appliedAt?: string;
  note?: string;
};

export type StockSummary = {
  itemNo: string;
  description?: string;
  barcode?: string;
  lots: Array<{
    lotNo: string;
    expirationDate?: string;
    locationCode: string;
    remaining: number;       // raw from Ledger
    reserved: number;        // sum of qty held in any Transfer (open or closed)
    available: number;       // remaining - reserved
    uom?: string;
  }>;
};
